# Generated by Django 3.2.7 on 2021-10-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
